[env] ## tells cargo make that we're in the context of a Cargo workspace
DOCKER_BUILD_TAG = "realworld_leptos"
DOCKER_LEPTOS_SITE_ADDR = "0.0.0.0:80"

[tasks.run]
env = { "RUST_ENV" = "development" }
install_crate = "cargo-leptos"
command = "cargo"
args = ["leptos", "watch"]

[tasks.test]
env = { "RUST_ENV" = "development" }
install_crate = "cargo-leptos"
command = "cargo"
args = ["leptos", "test"]

[tasks.e2e]
env = { "RUST_ENV" = "development" }
install_crate = "cargo-leptos"
command = "cargo"
args = ["leptos", "end-to-end"]

[tasks.refresh]
install_crate = "cargo-leptos"
command = "./scripts/refresh.sh"

[tasks.docker-build]
command = "docker"
args = ["build", ".", "-t", "${DOCKER_BUILD_TAG}"]

[tasks.docker-run]
command = "docker"
args = [
    "run",
    "-d",
    "-e",
    "LEPTOS_SITE_ADDR=${DOCKER_LEPTOS_SITE_ADDR}",
    "--name",
    "${DOCKER_BUILD_TAG}",
    "-p",
    "3000:80",
    "${DOCKER_BUILD_TAG}",
]

[tasks.docker-stop]
command = "docker"
args = ["stop", "${DOCKER_BUILD_TAG}"]

[tasks.docker-start]
command = "docker"
args = ["stop", "${DOCKER_BUILD_TAG}"]

[tasks.docker-restart]
dependencies = ["docker-stop", "docker-rm", "docker-run"]

[tasks.docker-rm]
command = "docker"
args = ["rm", "${DOCKER_BUILD_TAG}"]

[tasks.docker-rebuild]
dependencies = ["docker-stop", "docker-rm", "docker-build"]
