name: Run CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Build for release
        run: cargo build --release

      - name: Run unit tests
        run: cargo test --quiet

      - name: Install nightly toolchain
        run: rustup toolchain install nightly

      - name: Add rust fmt
        run: rustup component add rustfmt clippy --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Run clippy
        run: cargo clippy -v

      - name: Run rust formatter checks
        run: cargo fmt --all -- --check
